#https://beets.readthedocs.io/en/v1.4.7/reference/config.html
# This is default non-interactive config with:
# - non-interactive (quiet) run in skipping mode
# - no auto fingerprinting with acoustid chroma
# - relaxed tags requirements on match with relaxed thresholds
# - keeping files in place
# - using everything not matching as-is for further usage
#
directory: /mnt/dietpi_userdata/downloads
library: /mnt/dietpi_userdata/downloads.db
import:
    log: /var/log/slscripts/beets-import.log
    quiet: yes
    move: no
    copy: no
    write: yes
    from_scratch: no
    resume: yes
    incremental: yes
    quiet_fallback: asis
    none_rec_action: skip
    default_action: asis
    duplicate_action: skip
    detail: yes
    singletons: yes
match:
    strong_rec_thresh: 0.35
    medium_rec_thresh: 0.50
    rec_gap_thresh: 0.01
    required: album year artist title
asciify_paths: yes
paths:
        default: ${artist}-${album}%aunique{} - ${track}-${title}
        singleton: ${artist} - ${title}
plugins: chroma mbsync fromfilename badfiles replaygain fetchart embedart
chroma:
    auto: no
acoustid:
    apikey: DlrKDAjx8v
replaygain:
    auto: no
    overwrite: no
    backend: command
#backend options: gstreamer, command, audiotools, bs1770gain. Default: command.
#targetlevel: 89
fetchart:
    auto: yes
    cautious: true
    sources: coverart amazon albumart
embedart:
    auto: yes
    remove_art_file: yes
badfiles:
    commands:
        ogg: myoggchecker --opt1 --opt2
        flac: flac --test --warnings-as-errors --silent
        mp3: mp3val -f -t -si -nb -l/var/log/slscripts/beets-mp3val.log
